services:
  bouquet:
    build: .
    restart: unless-stopped
    pids_limit: 256
    mem_limit: 512M
    cpus: 0.5
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    environment:
      - DB=/data/bouquets.db
      - SECRET=/data/secret
